# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d52a8d4eb0104ad0380933ecb04228407425904ee465005240dd4aa23abacc4147e14163dff33680c7cc5b5cdffaff2417d21b80b28591bdb61a49813fc28eda

test:
  secret_key_base: a8148b031c7799a79fb445156156ee9e8bad2ecd80c516578829101053bd2d1870134d37bc561c6c29726ace894b3a5c484615d1ca3757c97c4f767b0b1d2019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
